# Generated by Django 5.1.2 on 2025-02-20 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_appuser_personal_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='profile_picture',
        ),
    ]
