# Generated by Django 5.1.2 on 2025-02-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userstatusupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatusupdate',
            name='status_title',
            field=models.CharField(default='Untitled Status', max_length=150),
        ),
    ]
