# Generated by Django 5.1.2 on 2025-02-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userstatusupdate_status_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatusupdate',
            name='status_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
