# Generated by Django 5.1.2 on 2025-02-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userstatusupdate_status_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='profile_photo',
            field=models.ImageField(default='default_profile.jpg', upload_to='profile_photos/'),
        ),
    ]
