# Generated by Django 5.1.2 on 2025-02-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_appuser_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profile/default_profile.jpg', null=True, upload_to='profile_photos/'),
        ),
    ]
