# Generated by Django 5.1.2 on 2025-02-28 07:07

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_appuser_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profile_photo',
            field=models.ImageField(blank=True, default='default_profile.jpg', null=True, upload_to=users.models.generate_uuid),
        ),
    ]
