# Generated by Django 5.1.2 on 2025-02-23 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_alter_userstatusupdate_status_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=150)),
                ('course_description', models.TextField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='users.appuser')),
                ('enrolled_students', models.ManyToManyField(blank=True, related_name='enrolled_students', to='users.appuser')),
            ],
        ),
    ]
