# Generated by Django 5.1.2 on 2025-02-25 15:21

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursematerial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='file',
            field=models.FileField(upload_to=courses.models.generate_uuid),
        ),
    ]
